### ISSUE TITLE
referencing destroyed object

### ISSUE THREAD

**Issue by tomquas** [viktor-shmigol/electron-windows-badge#5]
current release of this package produces the following error when creating a second Badge instance in the app – for example after closing a main window and opening a new one...

```
Uncaught Exception:
Error: Object has been destroyed
    at BadgeGenerator.generate (/Users/tom/projects/webde-desktop/node_modules/electron-windows-badge/badge_generator.js:18:21)
    at Badge.update (/Users/tom/projects/webde-desktop/node_modules/electron-windows-badge/index.js:16:22)
    at EventEmitter.ipcMain.on (/Users/tom/projects/webde-desktop/node_modules/electron-windows-badge/index.js:28:12)
    at EventEmitter.emit (events.js:187:15)
    at WebContents.<anonymous> (/Users/tom/projects/webde-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:355:13)
    at WebContents.emit (events.js:182:13
```

to fix this, i had to remove stale listeners:

```
 initListeners() {
+    ipcMain.removeAllListeners(UPDATE_BADGE_EVENT);
    ipcMain.on(UPDATE_BADGE_EVENT, (event, badgeNumber) => {
```

**Comment by viktor-shmigol** [comment]
@tomquas Thanks for letting me know. I've fixed it. Please, upgrade electron-windows-badge to 1.0.5
